version: '3'
services:
    evora-ols-dataload:
      image: ghcr.io/ebispot/ols4-dataload:dev
      volumes:
        - evora-ols-solr-data:/opt/solr/server/solr:rw
        - evora-ols-neo4j-data:/opt/neo4j/data:rw
        - ./ols_config_combined.json:/mnt/config/config.json:ro
        - ./out:/opt/dataload/out:ro
      command: ./dataload.dockersh --loadLocalFiles
    evora-ols-solr:
      image: solr:9.8.1
      environment:
        - SOLR_HOME=/mnt/evora-ols-solr-data
        - JAVA_OPTS=--add-modules jdk.incubator.vector
      ports:
        - 8983:8983
      volumes:
        - evora-ols-solr-data:/mnt/evora-ols-solr-data
      command: ["-f"]
      depends_on:
        evora-ols-dataload:
          condition: service_completed_successfully
    evora-ols-neo4j:
      image: neo4j:2025.03.0-community
      ports:
        - 7474:7474
        - 7687:7687
      volumes:
        - evora-ols-neo4j-data:/var/lib/neo4j/data
      environment:
        - NEO4J_AUTH=none
        - JAVA_OPTS=--add-modules jdk.incubator.vector
      depends_on:
        evora-ols-dataload:
          condition: service_completed_successfully
    evora-ols-backend:
      image: ghcr.io/ebispot/ols4-backend:dev
      ports:
        - 8080:8080
      environment:
        - OLS_SOLR_HOST=http://evora-ols-solr:8983
        - OLS_NEO4J_HOST=bolt://evora-ols-neo4j:7687
      depends_on:
        - evora-ols-solr
        - evora-ols-neo4j    
      links:
        - evora-ols-solr
        - evora-ols-neo4j 
    evora-ols-frontend:
      image: ghcr.io/ebispot/ols4-frontend:dev
      env_file: .env.evora_ols
      ports:
        - 8081:8080
      depends_on:
        - evora-ols-backend
      links:
        - evora-ols-backend
volumes:
    evora-ols-solr-data:
    evora-ols-neo4j-data:



